// constants/comingSoonMovies.ts

export const comingSoonMovies = [
    {
      id: "101",
      title: "Dune: Part Two",
      duration: "2h 35m",
      ageRating: "PG-13",
      rating: 4.9,
      description: "Paul Atreides unites with the Fremen and seeks revenge against the conspirators who destroyed his family.",
      image: "https://image.tmdb.org/t/p/w500/2rYvuJ8O4x1sVdOsbE3wVmtYdTy.jpg",
    },
    {
      id: "102",
      title: "Deadpool 3",
      duration: "TBD",
      ageRating: "TBD",
      rating: 0,
      description: "Deadpool teams up with Wolverine in a chaotic multiverse journey.",
      image: "https://image.tmdb.org/t/p/w500/8GnWDLn2AhnmkQ7hlQ9NJUYobSS.jpg",
    },
    {
      id: "103",
      title: "Mission: Impossible – Dead Reckoning Part Two",
      duration: "TBD",
      ageRating: "PG-13",
      rating: 0,
      description: "Ethan Hunt returns for another high-stakes mission.",
      image: "https://image.tmdb.org/t/p/w500/NNxYkU70HPurnNCSiCjYAmacwm.jpg",
    },
    {
      id: "104",
      title: "The Marvels",
      duration: "1h 45m",
      ageRating: "PG-13",
      rating: 3.9,
      description: "Carol Danvers, Kamala Khan, and Monica Rambeau begin swapping places every time they use their powers.",
      image: "https://image.tmdb.org/t/p/w500/9GBhzXMFjgcZ3FdR9w3bUMMTps5.jpg",
    },
    {
      id: "105",
      title: "The Hunger Games: The Ballad of Songbirds and Snakes",
      duration: "2h 37m",
      ageRating: "PG-13",
      rating: 4.3,
      description: "A prequel to The Hunger Games focusing on Coriolanus Snow.",
      image: "https://image.tmdb.org/t/p/w500/mBaXZ95R2OxueZhvQbcEWy2DqyG.jpg",
    },
    {
      id: "106",
      title: "Wonka",
      duration: "1h 57m",
      ageRating: "PG",
      rating: 4.0,
      description: "A young Willy Wonka embarks on a journey to become the world's greatest inventor, magician, and chocolate-maker.",
      image: "https://image.tmdb.org/t/p/w500/qhb1qOilapbapxWQn9jtRCMwXJF.jpg",
    },
    {
      id: "107",
      title: "Aquaman and the Lost Kingdom",
      duration: "2h 4m",
      ageRating: "PG-13",
      rating: 3.8,
      description: "Aquaman forges an uneasy alliance to save Atlantis and the world.",
      image: "https://image.tmdb.org/t/p/w500/8xV47NDrjdZDpkVcCFqkdHa3T0C.jpg",
    },
    {
      id: "108",
      title: "Inside Out 2",
      duration: "TBD",
      ageRating: "G",
      rating: 0,
      description: "Return to Riley's mind as she navigates teenage emotions.",
      image: "https://image.tmdb.org/t/p/w500/tK1zy5BsCt1J4OzoDicXmr0UTFH.jpg",
    },
    {
      id: "109",
      title: "Kung Fu Panda 4",
      duration: "TBD",
      ageRating: "PG",
      rating: 0,
      description: "Po returns for another martial arts adventure in the Valley of Peace.",
      image: "https://image.tmdb.org/t/p/w500/kDp1vUBnMpe8ak4rjgl3cLELqjU.jpg",
    },
    {
      id: "110",
      title: "Despicable Me 4",
      duration: "TBD",
      ageRating: "PG",
      rating: 0,
      description: "Gru and the Minions are back with more mischievous plans.",
      image: "https://image.tmdb.org/t/p/w500/5Xwuwv3fuRjZ6ftN3cV4eUJXHXV.jpg",
    },
    {
      id: "111",
      title: "Venom: The Last Dance",
      duration: "TBD",
      ageRating: "PG-13",
      rating: 0,
      description: "Eddie Brock and Venom face their most dangerous enemy yet.",
      image: "https://image.tmdb.org/t/p/w500/h5UzYZquMwO9FVn15R2eK2itmHu.jpg",
    },
    {
      id: "112",
      title: "Fantastic Four",
      duration: "TBD",
      ageRating: "TBD",
      rating: 0,
      description: "Marvel's first family returns with a rebooted MCU adventure.",
      image: "https://image.tmdb.org/t/p/w500/eDps4iT2EctprXkF8q9jQduugMS.jpg",
    },
    {
      id: "113",
      title: "Captain America: Brave New World",
      duration: "TBD",
      ageRating: "PG-13",
      rating: 0,
      description: "Sam Wilson takes up the shield in a post-Endgame world.",
      image: "https://image.tmdb.org/t/p/w500/8u5YJY9k7v5Mxyztw0PceR43Yqk.jpg",
    },
    {
      id: "114",
      title: "Blade",
      duration: "TBD",
      ageRating: "R",
      rating: 0,
      description: "A half-vampire, half-mortal man becomes a protector of humans against vampires.",
      image: "https://image.tmdb.org/t/p/w500/kehNnUtwqKgRu2xUAgGzJUUW8mA.jpg",
    },
    {
      id: "115",
      title: "Wicked",
      duration: "TBD",
      ageRating: "PG",
      rating: 0,
      description: "A modern retelling of the witches of Oz before Dorothy arrived.",
      image: "https://image.tmdb.org/t/p/w500/r57vVnYlEObYNWZLHrQacGFGNwv.jpg",
    },
    {
      id: "116",
      title: "How to Train Your Dragon (Live Action)",
      duration: "TBD",
      ageRating: "PG",
      rating: 0,
      description: "A new live-action adaptation of the beloved animated fantasy.",
      image: "https://image.tmdb.org/t/p/w500/hqkIcbrOHL86UncnHIsHVcVmzue.jpg",
    }
  ];
  