// mockMovies

export const movies = [
  {
    id: "1",
    title: "Inception",
    duration: "2h 28m",
    ageRating: "PG-13",
    rating: 4.8,
    description: "A thief who steals corporate secrets through dream-sharing technology is given the inverse task of planting an idea into the mind of a CEO.",
    image: "https://image.tmdb.org/t/p/w500/edv5CZvWj09upOsy2Y6IwDhK8bt.jpg",
  },
  {
    id: "2",
    title: "Interstellar",
    duration: "2h 49m",
    ageRating: "PG-13",
    rating: 4.7,
    description: "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
    image: "https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg",
  },
  {
    id: "3",
    title: "The Dark Knight",
    duration: "2h 32m",
    ageRating: "PG-13",
    rating: 4.9,
    description: "When the menace known as the Joker emerges, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
    image: "https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
  },
  {
    id: "4",
    title: "Avengers: Endgame",
    duration: "3h 1m",
    ageRating: "PG-13",
    rating: 4.6,
    description: "After the devastating events of Infinity War, the Avengers assemble once more to reverse Thanos' actions and restore balance.",
    image: "https://image.tmdb.org/t/p/w500/or06FN3Dka5tukK1e9sl16pB3iy.jpg",
  },
  {
    id: "5",
    title: "Avatar",
    duration: "2h 42m",
    ageRating: "PG-13",
    rating: 4.3,
    description: "A paraplegic Marine dispatched to the moon Pandora becomes torn between following his orders and protecting the world he feels is his home.",
    image: "https://image.tmdb.org/t/p/w500/5nklLFSZSagTJu3iEt3G41T9Uvh.jpg",
  },
  {
    id: "6",
    title: "The Matrix",
    duration: "2h 16m",
    ageRating: "R",
    rating: 4.7,
    description: "A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.",
    image: "https://image.tmdb.org/t/p/w500/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg",
  },
  {
    id: "7",
    title: "Spider-Man: No Way Home",
    duration: "2h 28m",
    ageRating: "PG-13",
    rating: 4.5,
    description: "With Spider-Man's identity now revealed, Peter asks Doctor Strange for help. When the spell goes wrong, dangerous foes appear from other worlds.",
    image: "https://image.tmdb.org/t/p/w500/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg",
  },
  {
    id: "8",
    title: "Black Panther",
    duration: "2h 14m",
    ageRating: "PG-13",
    rating: 4.4,
    description: "T'Challa, heir to the hidden but advanced kingdom of Wakanda, must step forward to lead his people into a new future.",
    image: "https://image.tmdb.org/t/p/w500/uxzzxijgPIY7slzFvMotPv8wjKA.jpg",
  },
  {
    id: "9",
    title: "Joker",
    duration: "2h 2m",
    ageRating: "R",
    rating: 4.6,
    description: "In Gotham City, mentally troubled comedian Arthur Fleck is disregarded and mistreated by society, triggering his descent into madness.",
    image: "https://image.tmdb.org/t/p/w500/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg",
  },
  {
    id: "10",
    title: "Guardians of the Galaxy",
    duration: "2h 1m",
    ageRating: "PG-13",
    rating: 4.5,
    description: "A group of intergalactic criminals must pull together to stop a fanatical warrior with plans to purge the universe.",
    image: "https://image.tmdb.org/t/p/w500/3bKcTD8T2lEGJErxE8wT0Oe1GKW.jpg",
  },
  {
    id: "11",
    title: "Doctor Strange",
    duration: "1h 55m",
    ageRating: "PG-13",
    rating: 4.3,
    description: "While on a journey of physical and spiritual healing, a brilliant neurosurgeon is drawn into the world of the mystic arts.",
    image: "https://image.tmdb.org/t/p/w500/uGBVj3bEbCoZbDjjl9wTxcygko1.jpg",
  },
  {
    id: "12",
    title: "Iron Man",
    duration: "2h 6m",
    ageRating: "PG-13",
    rating: 4.6,
    description: "After being held captive in an Afghan cave, billionaire engineer Tony Stark creates a unique weaponized suit of armor to fight evil.",
    image: "https://image.tmdb.org/t/p/w500/78lPtwv72eTNqFW9COBYI0dWDJa.jpg",
  },
  {
    id: "13",
    title: "Deadpool",
    duration: "1h 48m",
    ageRating: "R",
    rating: 4.5,
    description: "A wisecracking mercenary gets experimented on and becomes immortal but ugly, and sets out to track down the man who ruined his looks.",
    image: "https://image.tmdb.org/t/p/w500/fSRb7vyIP8rQpL0I47P3qUsEKX3.jpg",
  },
  {
    id: "14",
    title: "The Batman",
    duration: "2h 56m",
    ageRating: "PG-13",
    rating: 4.5,
    description: "Batman ventures into Gotham City's underworld when a sadistic killer leaves behind a trail of cryptic clues.",
    image: "https://image.tmdb.org/t/p/w500/74xTEgt7R36Fpooo50r9T25onhq.jpg",
  },
  {
    id: "15",
    title: "Shang-Chi and the Legend of the Ten Rings",
    duration: "2h 12m",
    ageRating: "PG-13",
    rating: 4.2,
    description: "Shang-Chi must confront the past he thought he left behind when he is drawn into the web of the mysterious Ten Rings organization.",
    image: "https://image.tmdb.org/t/p/w500/1BIoJGKbXjdFDAqUEiA2VHqkK1Z.jpg",
  },
  {
    id: "16",
    title: "Dune",
    duration: "2h 35m",
    ageRating: "PG-13",
    rating: 4.4,
    description: "Paul Atreides, a brilliant and gifted young man born into a great destiny beyond his understanding, travels to the most dangerous planet in the universe.",
    image: "https://image.tmdb.org/t/p/w500/d5NXSklXo0qyIYkgV94XAgMIckC.jpg",
  },
  {
    id: "17",
    title: "Tenet",
    duration: "2h 30m",
    ageRating: "PG-13",
    rating: 4.1,
    description: "Armed with only one word—Tenet—and fighting for the survival of the entire world, a Protagonist journeys through a twilight world of international espionage.",
    image: "https://image.tmdb.org/t/p/w500/k68nPLbIST6NP96JmTxmZijEvCA.jpg",
  },
  {
    id: "18",
    title: "Thor: Ragnarok",
    duration: "2h 10m",
    ageRating: "PG-13",
    rating: 4.4,
    description: "Thor must escape the alien planet Sakaar in time to save Asgard from Hela and the impending Ragnarok.",
    image: "https://image.tmdb.org/t/p/w500/rzRwTcFvttcN1ZpX2xv4j3tSdJu.jpg",
  },
  {
    id: "19",
    title: "The Flash",
    duration: "2h 24m",
    ageRating: "PG-13",
    rating: 4.0,
    description: "Barry Allen uses his super speed to change the past, but his attempt to save his family creates a world without superheroes.",
    image: "https://image.tmdb.org/t/p/w500/rktDFPbfHfUbArZ6OOOKsXcv0Bm.jpg",
  },
  {
    id: "20",
    title: "The Marvels",
    duration: "1h 45m",
    ageRating: "PG-13",
    rating: 3.9,
    description: "Carol Danvers, Kamala Khan, and Monica Rambeau begin swapping places every time they use their powers and must team up.",
    image: "https://image.tmdb.org/t/p/w500/9GBhzXMFjgcZ3FdR9w3bUMMTps5.jpg",
  }
];
